version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    links:
      - "mongo"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"