@startuml
actor User
User -> Mobile: Login (phone, password)
Mobile -> Backend: POST /user/login (phone, password)
Backend -> Database: Find user (phone)
Database --> Backend: Response: user's information
Backend -> Backend: Authenticate user (password) and generate JWT token (userId)
Backend --> Mobile: Response: user's information, JWT token
Mobile -> User: Log user in
Mobile ->> Mobile: Store (user's information, JWT token)
loop jwt token expired
  User -> Mobile: Use features
  Mobile -> Backend: Request resources (Bearer JWT token, requestBody)
  Backend -> Backend: Validate JWT (JWT token): userId
  Backend -> Database: CRUD (query, userId)
  Database --> Backend: Response: data
  Backend --> Mobile: Response: payload
  Mobile --> User: Display: data
end
@enduml